name: task_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  objectbox: 4.1.0
  objectbox_flutter_libs: 4.1.0  # If targeting mobile
  encrypt: ^5.0.1  # For AES encryption


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
