name: task_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  objectbox: 4.1.0 # For local storage 
  objectbox_flutter_libs: 4.1.0 
  encrypt: ^5.0.1  # For AES encryption
  provider: ^6.0.3  # For state management
  flutter_slidable: ^2.0.0  # For slidable items
  intl: ^0.17.0  # For date and number formatting
  carousel_slider: ^5.0.0 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
